apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tabby-server.name" . }}-config
  labels:
    app: {{ include "tabby-server.name" . }}
stringData:
  config.toml: |
    {{- .Values.configFile | nindent 4 }}